src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChambreRepository::class)]
class Chambre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $descritpion_courte = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_longue = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column]
    private ?int $prix_journalier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'chambre', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescritpionCourte(): ?string
    {
        return $this->descritpion_courte;
    }

    public function setDescritpionCourte(string $descritpion_courte): static
    {
        $this->descritpion_courte = $descritpion_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(string $description_longue): static
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): static
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setChambre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getChambre() === $this) {
                $commande->setChambre(null);
            }
        }

        return $this;
    }
}

src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Chambre $chambre = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_arrivee = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_depart = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\Column]
    private ?int $prix_total = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChambre(): ?Chambre
    {
        return $this->chambre;
    }

    public function setChambre(?Chambre $chambre): static
    {
        $this->chambre = $chambre;

        return $this;
    }

    public function getDateArrivee(): ?\DateTimeInterface
    {
        return $this->date_arrivee;
    }

    public function setDateArrivee(\DateTimeInterface $date_arrivee): static
    {
        $this->date_arrivee = $date_arrivee;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): static
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getPrixTotal(): ?int
    {
        return $this->prix_total;
    }

    public function setPrixTotal(int $prix_total): static
    {
        $this->prix_total = $prix_total;

        return $this;
    }
}

src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: MembreRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Membre implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $civilite = null;

    #[ORM\Column]
    private ?int $statut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): static
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getStatut(): ?int
    {
        return $this->statut;
    }

    public function setStatut(int $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }
}

templates/app/chambre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Grand Horizon - Chambres{% endblock %}

{% block body %}

<div class="container">
    <h1 class="text-center mt-4 mb-4 titre titre-page">Chambres haut de gamme</h1>
    <p class="lead text-center">Des espaces élégants et raffinés pour un séjour inoubliable.</p>

    <div class="text-center">
        <img src="{{ asset('assets/img/chambre.jpg') }}" alt="Image 1" class="img-resto rounded">
        <p class="mt-3">Découvrez nos chambres haut de gamme, un mélange parfait de confort, de style et d'élégance, où chaque détail a été pensé pour créer un havre de paix lors de votre séjour.</p>
    </div>

    <div class="dish mt-4 mb-4">
        <div class="row d-flex align-items-center">
            <div class="col-md-8 text-center">
                <div class="description mt-4 mb-4">Nos chambres haut de gamme sont conçues pour répondre aux attentes des voyageurs les plus exigeants. Chaque détail a été soigneusement pensé pour vous offrir un espace élégant et raffiné, où le confort et la détente sont au rendez-vous. Des matériaux de qualité, une décoration moderne et des équipements haut de gamme sont autant d'éléments qui contribuent à créer une atmosphère unique et apaisante dans chaque chambre.</div>
                <div class="description mt-4 mb-4">Chaque chambre est un havre de paix, offrant un espace spacieux et confortable pour vous reposer et vous ressourcer. Les lits moelleux et les draps luxueux vous garantissent des nuits de sommeil réparateur. Les salles de bains privatives sont équipées d'installations modernes et de produits de toilette de qualité pour votre confort.</div>
            </div>
            <div class="col-md-4 d-flex justify-content-center">
                <img src="{{ asset('assets/img/chambre2.jpg') }}" alt="Image chambre" class="resto-img rounded">
            </div>
        </div>
    </div>

    <div class="dish mt-4 mb-4">
        <div class="row d-flex align-items-center">
            <div class="col-md-4 d-flex justify-content-center">
                <img src="{{ asset('assets/img/chambre3.jpg') }}" alt="Image chambre" class="resto-img rounded">
            </div>
            <div class="col-md-8 text-center">
                <div class="description mt-4 mb-4">Que vous soyez en voyage d'affaires ou en vacances, nos chambres sont conçues pour répondre à tous vos besoins. Un espace de travail fonctionnel, un accès Wi-Fi haut débit et une télévision à écran plat sont disponibles pour votre confort et votre divertissement. Profitez également des vues magnifiques sur la ville ou sur la nature environnante depuis certaines de nos chambres.</div>
                <div class="description mt-4 mb-4">Nous nous efforçons de créer une atmosphère chaleureuse et accueillante dans chaque chambre. L'éclairage doux, les couleurs apaisantes et les éléments décoratifs bien choisis créent une ambiance propice à la détente et à la tranquillité d'esprit. Profitez également des équipements supplémentaires tels que le minibar, le coffre-fort et le service d'étage pour rendre votre séjour encore plus agréable.</div>
            </div>
        </div>
    </div>

    <h2 class="text-center mt-4 mb-4">Les différents types de chambres</h2>
    
    <div class="container text-center mb-4">
        <button onclick="showCard('Chambre Classique')" class="btn btn-primary text-warning rounded">Chambre Classique</button>
        <button onclick="showCard('Chambre Confort')" class="btn btn-primary text-warning rounded">Chambre Confort</button>
        <button onclick="showCard('Grande Suite')" class="btn btn-primary text-warning rounded">Grande Suite</button>
    </div>

    <div class="row dish mt-4 mb-4 align-items-stretch text-center">
        {% for chambre in chambres %}
        <div class="col-md-12 h-75 chambre-card" data-title="{{ chambre.titre }}">
            <div class="card border-secondary shadow d-flex flex-column">
                <div class="card-header bg-primary rounded">
                    <img src="{{ asset('uploads/images/' ~ chambre.photo) }}" class="card-img-top rounded" alt="">
                </div>
                <div class="card-body bg-light">
                    <h5 class="fw-bold fst-italic text-center text-dark">{{ chambre.titre }}</h5>
                    <hr class="text-dark">
                    <p class="text-center text-primary">{{ chambre.descritpionCourte|slice(0, 100) }}</p>
                    <div class="card-footer">
                        <p class="card-text text-center text-primary fw-bold">Prix: {{ chambre.prixJournalier / 100 }}€</p>
                        <div class="text-center my-3">
                            <a href="{{ path('show_chambre', { id: chambre.id }) }}" class="btn btn-primary text-warning rounded">Voir les détails</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    

</div>
<footer class="bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="footer">
          <div>
          <p class="footer-text my-3">&copy; 2023 Hôtel Grand Horizon. Tous droits réservés.</p>
        </div>
          <div class="footer-icons">
            <a href="https://fr-fr.facebook.com/" target="_blank" class="social-icon"><i class="fa-brands fa-facebook text-warning fa-2xl"></i></a>
            <a href="https://www.instagram.com/" target="_blank" class="social-icon"><i class="fa-brands fa-instagram text-warning fa-2xl"></i></a>
          </div>
        </div>
        </div>
      </div>
    </div>
  </footer>
<a href="#" class="scroll-to-top" title="Remonter en haut de la page">&#8593;</a>
<script src="{{ asset('assets/js/chambre.js')}}"></script>
<script src="{{ asset('assets/js/main.js') }}"></script>
{% endblock %}

templates/app/showChambre.html.twig
{% extends "base.html.twig" %}
    
{% block title %}
Grand Horizon - Chambre
{% endblock title %}

{% block body %}

{% for flashMessage in app.flashes('danger') %}
    <div class="alert alert-danger text-center">
        {{ flashMessage }}
    </div>
{% endfor %}


<div class="text-center container mb-5">
    <h1 class="text-center mt-4 mb-4 titre titre-page">{{chambre.titre}}</h1>
    <p class="mt-3 lead">{{chambre.descritpionCourte}}</p>
    <img src="{{ asset('uploads/images/' ~ chambre.photo) }}" alt="Image 1" class="img-resto rounded">
    

    <p class="mt-3">{{chambre.descriptionLongue|raw}}</p>
    <div class="btn-price mt-5">
        <p class="fw-bold h5">Prix Journalier : {{chambre.prixJournalier / 100}}€</p>
    </div>
    <hr>    
    {# <a href="{{ path('form_commande', {id: chambre.id}) }}" class="btn btn-primary text-warning rounded">Reservez-votre chambre</a> #}

    <a href="" id="btnAjouterCommentaire" class="btn btn-primary text-warning rounded">Reservez-votre chambre</a>


    <div id="formulaireCommentaire" class="mb-5 mt-5 container" style="display: none;">

      {{ form_start(commandeForm) }}
      <div class="row mx-3">
        <p class="text-center mb-4 h4">Vos coordonnées</p>
            <div class="cold-md-6">
                {{ form_row(commandeForm.prenom) }}
            </div>
            <div class="cold-md-6">
                {{ form_row(commandeForm.nom) }}
            </div>
            <div class="cold-md-6">
                {{ form_row(commandeForm.telephone) }}
            </div>
            <div class="cold-md-6">
                {{ form_row(commandeForm.email) }}
            </div>     
            <p class="text-center h4 mt-2">Choisissez vos dates</p>       
                {{ form_row(commandeForm.date_arrivee) }}
                        
                {{ form_row(commandeForm.date_depart) }}

            <p>Prix total : {{commande.prixTotal }}€</p>
        </div>                
            <div class="text-center">
                <button class="btn btn-primary text-warning rounded mt-4" type="submit">Valider</button>
            </div>
        
        {{ form_end(commandeForm) }}
    
    </div>
</div>
    
<footer class="bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="footer">
          <div>
          <p class="footer-text my-3">&copy; 2023 Hôtel Grand Horizon. Tous droits réservés.</p>
        </div>
          <div class="footer-icons">
            <a href="https://fr-fr.facebook.com/" target="_blank" class="social-icon"><i class="fa-brands fa-facebook text-warning fa-2xl"></i></a>
            <a href="https://www.instagram.com/" target="_blank" class="social-icon"><i class="fa-brands fa-instagram text-warning fa-2xl"></i></a>
          </div>
        </div>
        </div>
      </div>
    </div>
  </footer>
  <a href="#" class="scroll-to-top" title="Remonter en haut de la page">&#8593;</a>
  <script src="{{ asset('assets/js/main.js')}}"></script>
  <script src="{{ asset('assets/js/formComment.js')}}"></script>

{% endblock body %}

templates/app/showCommande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Historique de commandes{% endblock %}

{% block body %}

    <h1 class="text-center mt-4 titre">Historique de commandes</h1>
    <div class="table-responsive">
    <table class="table mt-4 text-center">
        <thead class="table-dark">
            <tr>
                <th class="text-center">ID</th>
                <th class="text-center">Chambre</th>
                <th class="text-center">Photo</th>
                <th class="text-center">Date d'arrivée</th>
                <th class="text-center">Date de départ</th>
                <th class="text-center">Prix total</th>
                <th class="text-center">Prénom</th>
                <th class="text-center">Nom</th>
                <th class="text-center">Téléphone</th>
                <th class="text-center">Email</th>
                <th class="text-center">Date d'enregistrement</th>
            </tr>
        </thead>
        <tbody class="table-warning">
            {% for commande in commandes %}
            <tr>
                <td class="text-center">{{ commande.id }}</td>
                <td class="text-center">{{ commande.chambre.titre }}</td>
                <td class="text-center"><img src="{{ asset('uploads/images/' ~ commande.chambre.photo) }}" alt="" class="commande-photo"></td>
                <td class="text-center">{{ commande.dateArrivee|date('d/m/Y') }}</td>
                <td class="text-center">{{ commande.dateDepart|date('d/m/Y') }}</td>
                <td class="text-center">{{ commande.prixTotal/100 }}€</td>
                <td class="text-center">{{ commande.prenom }}</td>
                <td class="text-center">{{ commande.nom }}</td>
                <td class="text-center">{{ '%010s'|format(commande.telephone) }}</td>
                <td class="text-center">{{ commande.email }}</td>
                <td class="text-center">{{ commande.dateEnregistrement|date('d/m/Y H:i:s') }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>


    <footer class="bg-primary">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="footer">
            <div>
            <p class="footer-text my-3">&copy; 2023 Hôtel Grand Horizon. Tous droits réservés.</p>
          </div>
            <div class="footer-icons">
              <a href="https://fr-fr.facebook.com/" target="_blank" class="social-icon"><i class="fa-brands fa-facebook text-warning fa-2xl"></i></a>
              <a href="https://www.instagram.com/" target="_blank" class="social-icon"><i class="fa-brands fa-instagram text-warning fa-2xl"></i></a>
            </div>
          </div>
          </div>
        </div>
      </div>
    </footer>



  <a href="#" class="scroll-to-top" title="Remonter en haut de la page">&#8593;</a>
  <script src="{{ asset('assets/js/main.js')}}"></script>
{% endblock %}

templates/app/showCommentaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaires{% endblock %}

{% block body %}

    <h1 class="text-center mt-4 mb-4 titre">Historique des commentaires</h1>
    
    {% for commentaire in commentaires %}
    <div class="commentaire-card mb-12 text-center mb-4 " id="massage-relaxant">
        <h3>{{ commentaire.prenom }} {{commentaire.nom}}</h3>
        <div class="dish">
          <div class="row d-flex align-items-center">
                       
            <div class="col-md-4">
                <div class="name">{{commentaire.email}}</div>
                <div class="name mt-2">{{commentaire.category}}</div>
                <div class="price mt-3 mb-3">{{ commentaire.dateEnregistrement|date('d/m/Y H:i:s') }}</div>
                {% if commentaire.note == 1 %}
                <div><i class="fa-solid fa-star text-warning"></i></div>
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
                {% elseif commentaire.note == 2 %}
                <div>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-regular fa-star"></i>
                    <i class="fa-regular fa-star"></i>
                    <i class="fa-regular fa-star"></i>
                </div>

                {% elseif commentaire.note == 3 %}
                <div>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-regular fa-star"></i>
                    <i class="fa-regular fa-star"></i>
                </div>
                {% elseif commentaire.note == 4 %}
                <div>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-regular fa-star"></i>
                </div>
                {% elseif commentaire.note == 5 %}
                <div>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-solid fa-star text-warning"></i>
                    <i class="fa-solid fa-star text-warning"></i>
                </div>
                {% else %}
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
                {% endif %}             
            </div>
            <div class="col-md-8 text-center">
              <div class="description mt-4 mb-4">{{commentaire.contenu|raw}}</div>
            </div> 
          </div>
        </div>
    </div>
    {% endfor %}

    <div class="text-center">
    <a class="btn btn-primary text-warning rounded mb-4" href="" id="btnAjouterCommentaire">Ajouter un Commentaire</a>
    </div>

    <div id="formulaireCommentaire" class="mb-5 container" style="display: none;">
        <h2 class="text-center mt-4">Laissez nous un commentaire</h2>

        {{ form_start(form) }}
        <div class="row mx-3">
            <div class="col-md-6">
              {{ form_row(form.prenom) }}
            </div>
            <div class="col-md-6">
            {{ form_row(form.nom)}}
            </div>
            <div class="col-md-6"> 
            {{ form_row(form.email)}}
            </div>
            <div class="col-md-6"> 
            {{ form_row(form.note)}}
            </div>
            {{ form_row(form.category)}}
            {{ form_row(form.contenu)}}
        </div>
        <div class="text-center">
            <button class="btn btn-primary mt-2 rounded text-warning" type="submit">Valider</button>
        </div>
        {{ form_end(form) }}
    </div>

    <footer class="bg-primary">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="footer">
            <div>
            <p class="footer-text my-3">&copy; 2023 Hôtel Grand Horizon. Tous droits réservés.</p>
          </div>
            <div class="footer-icons">
              <a href="https://fr-fr.facebook.com/" target="_blank" class="social-icon"><i class="fa-brands fa-facebook text-warning fa-2xl"></i></a>
              <a href="https://www.instagram.com/" target="_blank" class="social-icon"><i class="fa-brands fa-instagram text-warning fa-2xl"></i></a>
            </div>
          </div>
          </div>
        </div>
      </div>
    </footer>
 

      <a href="#" class="scroll-to-top" title="Remonter en haut de la page">&#8593;</a>
      <script src="{{ asset('assets/js/main.js')}}"></script>
      <script src="{{ asset('assets/js/formComment.js')}}"></script>
</body>
{% endblock %}